### ISSUE TITLE
[Refactor/Upgrade] Migrate the all repository from Cairo 2.2.0 to 2.6.0 - Big Issue

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-contracts#39]
**Description**
---
Upgrade the all repository from Cairo 2.2.0 to 2.6.0 with it's dependencies 

Additional Information
---------------------------
[ High Difficulty  - Cairo - Medium Priority]

**Acceptance Criteria**
---

- [ ] Deployed a version of 2.2.0 on testnet - Sepolia
- [ ] Do the refactor/upgrade from Cairo 2.2.0 to 2.6.0
- [ ] Do the upgrade on the smart contract on testnet - Sepolia
- [ ] Ensure that the Carbon Protocol still working

**Comment by TAdev0** [comment]
Hi @cloudvenger  @Khyati729 , may i be assigned to this issue?
Thank you.

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by kfastov** [comment]
Hello! Can I please take this issue?

**Comment by kfastov** [comment]
Hello! Still working on this. I'll hope I'll make it today or tomorrow. Here's a draft [PR](https://github.com/carbonable-labs/cairo-erc-3525/pull/40):
